-- -----------------------------------------------------
-- Table `blog`.`user`
-- -----------------------------------------------------
INSERT INTO `blog`.`user`
    (pseudo, email, password, role, status)
VALUES
    ('simon', 'fenrir0680@gmail.com', '4c53c523128b86ae4256ace325f71273085aae88f4a4da2fae181c9c419612bc', 'Administrator', 'authorized'),
    ('test', 'test@test.com', '4c53c523128b86ae4256ace325f71273085aae88f4a4da2fae181c9c419612bc', 'Subscriber', 'banned'),
    ('test2', 'test2@test.com', '4c53c523128b86ae4256ace325f71273085aae88f4a4da2fae181c9c419612bc', 'Subscriber', 'banned')
;

-- -----------------------------------------------------
-- Table `blog`.`post`
-- -----------------------------------------------------
INSERT INTO `blog`.`post`
    (author_id, title, post, creationDate, modificationDate, status)
VALUES
    (1, 'Premier Post', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean porta sapien ut arcu mattis, ut tempus lorem mattis. Quisque ut ligula sed magna viverra egestas. Aliquam rhoncus finibus fringilla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent at nunc non elit mattis consequat consectetur et mi. Phasellus et commodo magna. Curabitur nec lacus dictum, bibendum tellus faucibus, sodales purus. Integer et rutrum metus. Etiam mauris augue, rutrum ac viverra et, molestie eu nisi. Quisque ipsum quam, tempor vitae mi ut, egestas consectetur purus. Ut tortor nunc, viverra vestibulum lectus vitae, convallis consectetur orci. Phasellus at iaculis odio.

Sed et eleifend lacus, ut gravida ipsum. Curabitur pellentesque neque libero, eget laoreet sem rhoncus elementum. Quisque quis velit eros. Cras ut velit at massa euismod efficitur quis eu arcu. Suspendisse porttitor maximus ornare. Sed sit amet bibendum justo, quis congue tellus. Ut consequat mattis viverra. Sed id facilisis urna, sit amet ultrices lacus. Proin non sapien vel est tincidunt fringilla sed ac sem. Curabitur rhoncus accumsan lacinia. Pellentesque pellentesque, velit a blandit ultricies, elit orci varius tortor, nec tristique ante mi eu ex.', '2017-10-16', '2018-01-08', 'Publish'),
    (1, 'Deuxième Post', ' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean porta sapien ut arcu mattis, ut tempus lorem mattis. Quisque ut ligula sed magna viverra egestas. Aliquam rhoncus finibus fringilla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent at nunc non elit mattis consequat consectetur et mi. Phasellus et commodo magna. Curabitur nec lacus dictum, bibendum tellus faucibus, sodales purus. Integer et rutrum metus. Etiam mauris augue, rutrum ac viverra et, molestie eu nisi. Quisque ipsum quam, tempor vitae mi ut, egestas consectetur purus. Ut tortor nunc, viverra vestibulum lectus vitae, convallis consectetur orci. Phasellus at iaculis odio.

Sed et eleifend lacus, ut gravida ipsum. Curabitur pellentesque neque libero, eget laoreet sem rhoncus elementum. Quisque quis velit eros. Cras ut velit at massa euismod efficitur quis eu arcu. Suspendisse porttitor maximus ornare. Sed sit amet bibendum justo, quis congue tellus. Ut consequat mattis viverra. Sed id facilisis urna, sit amet ultrices lacus. Proin non sapien vel est tincidunt fringilla sed ac sem. Curabitur rhoncus accumsan lacinia. Pellentesque pellentesque, velit a blandit ultricies, elit orci varius tortor, nec tristique ante mi eu ex.', '2017-11-16', '2018-01-10', 'Publish'),
    (1, 'Et un troisième', ' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean porta sapien ut arcu mattis, ut tempus lorem mattis. Quisque ut ligula sed magna viverra egestas. Aliquam rhoncus finibus fringilla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent at nunc non elit mattis consequat consectetur et mi. Phasellus et commodo magna. Curabitur nec lacus dictum, bibendum tellus faucibus, sodales purus. Integer et rutrum metus. Etiam mauris augue, rutrum ac viverra et, molestie eu nisi. Quisque ipsum quam, tempor vitae mi ut, egestas consectetur purus. Ut tortor nunc, viverra vestibulum lectus vitae, convallis consectetur orci. Phasellus at iaculis odio.

Sed et eleifend lacus, ut gravida ipsum. Curabitur pellentesque neque libero, eget laoreet sem rhoncus elementum. Quisque quis velit eros. Cras ut velit at massa euismod efficitur quis eu arcu. Suspendisse porttitor maximus ornare. Sed sit amet bibendum justo, quis congue tellus. Ut consequat mattis viverra. Sed id facilisis urna, sit amet ultrices lacus. Proin non sapien vel est tincidunt fringilla sed ac sem. Curabitur rhoncus accumsan lacinia. Pellentesque pellentesque, velit a blandit ultricies, elit orci varius tortor, nec tristique ante mi eu ex.', '2018-01-10', '2018-01-10', 'Publish'),
    (1, 'Quatre', ' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean porta sapien ut arcu mattis, ut tempus lorem mattis. Quisque ut ligula sed magna viverra egestas. Aliquam rhoncus finibus fringilla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent at nunc non elit mattis consequat consectetur et mi. Phasellus et commodo magna. Curabitur nec lacus dictum, bibendum tellus faucibus, sodales purus. Integer et rutrum metus. Etiam mauris augue, rutrum ac viverra et, molestie eu nisi. Quisque ipsum quam, tempor vitae mi ut, egestas consectetur purus. Ut tortor nunc, viverra vestibulum lectus vitae, convallis consectetur orci. Phasellus at iaculis odio.

Sed et eleifend lacus, ut gravida ipsum. Curabitur pellentesque neque libero, eget laoreet sem rhoncus elementum. Quisque quis velit eros. Cras ut velit at massa euismod efficitur quis eu arcu. Suspendisse porttitor maximus ornare. Sed sit amet bibendum justo, quis congue tellus. Ut consequat mattis viverra. Sed id facilisis urna, sit amet ultrices lacus. Proin non sapien vel est tincidunt fringilla sed ac sem. Curabitur rhoncus accumsan lacinia. Pellentesque pellentesque, velit a blandit ultricies, elit orci varius tortor, nec tristique ante mi eu ex.', '2018-01-10', '2018-01-10', 'Pending');
